### ISSUE TITLE
Activation email from forum not received

### ISSUE THREAD

**Issue by axgdev** [HotaruCMS/HotaruCMS#99]
I know that I should not post this here but... I want to download plugins or themes from the forum but it has been impossible as I don't receive the activation email to have my account active.. I tried with other email and it doesn't work either.. I'm checking spam and it is not there either. I hope you are able to fix it! Kind regards

**Comment by shibuya246** [comment]
Thanks. I set your account as Approved in the forums now. Let me know if there is any other problem
